name: "Automatic Release"

on:
  push:
    branches:
      "master"

jobs:
  release:
    name: "Automatic Release"
    runs-on: "windows-latest"
    steps:
      - uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
