name: Automatic Release with Zip

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Build and Zip File]
    types:
      - completed

jobs:        
  release:
    name: Automatic Release
    runs-on: self-hosted
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Download ZIP file
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: build.yml
  
      - uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            VALocker.zip
          
