name: Build and Zip File

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Install PyInstaller
        run: |
          pip install pyinstaller

      - name: Build file with PyInstaller
        run: |
          pyinstaller --noconfirm --onefile --windowed --icon "images/icons/instalocker_enabled.ico" --add-data "data;data/" --add-data "images;images/" --collect-all "customtkinter" --distpath dist/ VALocker.pyw

      - name: Create ZIP file
        uses: edgarrc/action-7z@v1
        with:
          args: 7z a -r VALocker.zip data/* images/* dist/Valocker.exe -x!data/instalocker.py
        

      - name: Upload ZIP file
        uses: actions/upload-artifact@v3
        with:
          name: VALocker
          path: VALocker.zip
