# Name of the workflow
name: Release

# Run on every commit tag which begins with "v"
on:
  push:
    branches:
      - "master"

# Automatically create a GitHub Release
jobs:
  release:
    name: "Release"
    runs-on: "windows-latest"
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false