# Name of the workflow
name: "release"

# Run on every commit pushed to master
on:
  push:
    branches:
      - "master"

# Automatically create a GitHub Release
jobs:
  release:
    name: "Release"
    runs-on: "windows-latest"
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "latest"